### ISSUE TITLE
Unable to create native image using Java 11

### ISSUE THREAD

**Issue by ravening** [spring-tips/spring-and-graal-part-2#1]
Im using the compile.sh script to create a native image for "jpa" artifact but I cant create a native image using java 11. Below is my setup details and the errors

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

```
# java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```

```
# native-image --version
GraalVM Version 20.1.0 (Java Version 11.0.7)
```

```
WARNING GR-10238: VarHandle for static field is currently not fully supported. Static field private static volatile java.lang.System$Logger jdk.internal.event.EventHelper.securityLogger is not properly marked for Unsafe access!
[spring-boot-graalvm:7111]     (clinit):   3,189.89 ms,  5.39 GB
[spring-boot-graalvm:7111]   (typeflow):  90,467.28 ms,  5.39 GB
[spring-boot-graalvm:7111]    (objects): 113,131.77 ms,  5.39 GB
[spring-boot-graalvm:7111]   (features):  23,402.76 ms,  5.39 GB
[spring-boot-graalvm:7111]     analysis: 234,764.30 ms,  5.39 GB
[spring-boot-graalvm:7111]     universe:   8,485.35 ms,  5.39 GB
Error: Image build request failed with exit status 137
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 137
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1722)

real	4m45.168s
user	17m16.383s
sys	0m34.748s
```

**Comment by ravening** [comment]
It was a memory related issue which is mentioned in https://github.com/quarkusio/quarkus/issues/1140
